[package]
name = "mcts"
version = "0.1.0"
authors = ["Valentin Metz <Valentin.Metz@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
ansi-escapes = "0.1.1"
rand = "0.8.5"
